### PR TITLE
Initial rewrite of the DSS implementation leveraging CRDB for remote ID operations

### PR DESCRIPTION
**Pull request by steeling**

### CODE REVIEW

**Comment by jgrossmac** [comment]
@googlebot I consent.

**Comment by vosst** [comment]
@googlebot I consent.

**Comment by barroco** [comment]
@googlebot I consent.

**Comment by BenjaminPelletier** [comment]
@googlebot I fixed it.

**Comment by BenjaminPelletier** [comment]
CLA status verified for all 6 authors in this PR (steeling, vosst, jgrossmac, davidsansome, guille2718, barroco) and consent verified for [barroco](https://github.com/wing-aviation/InterUSS-Platform/pull/87#issuecomment-533225670), [vosst](https://github.com/wing-aviation/InterUSS-Platform/pull/87#issuecomment-531554403), and [jgrossmac](https://github.com/wing-aviation/InterUSS-Platform/pull/87#issuecomment-522628146).  The other three contributors are Google-affiliated and do not need separate consent.  @googlebot will not automatically set status to "ok" when author consent is needed, so I will set cla:yes according to this comment.

**Pull request merged**
